query ALL_POSTS_QUERY {
  posts(where: {categoryName: "En"}, first: 3) {
    nodes {
      title
      date
      id
      databaseId
      excerpt
      content
      slug
      categories {
        nodes {
          name
        }
      }
      tags {
        nodes {
          name
        }
      }
      featuredImage {
        node {
          altText
          sourceUrl
        }
      }
    }
  }
}

  