          query Galleries {
            galleries {
              nodes {
                title
                id
                slug
                acfgallery {
                  title
                  image {
                    sourceUrl
                    altText
                  }
                }
              }
            }
          }